const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  SUSPENDED: 'SUSPENDED',
};

const STUDENT_STATUS = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  PASSED_OUT: 'PASSED_OUT',
  DROPPED: 'DROPPED',
};

const STUDENT_GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
};

const TEACHER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLOCKED: 'BLOCKED',
};

const ACADEMIC_YEAR_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
};

const CLASS_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

const SECTION_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

const ENROLLMENT_STATUS = {
  ACTIVE: 'active',
  COMPLETED: 'completed',
};

const LEAD_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST',
};

const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
};

const FEE_STATUS = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
};

const PAYMENT_METHOD = {
  CASH: 'CASH',
  UPI: 'UPI',
  BANK: 'BANK',
};

module.exports = {
  USER_STATUS,
  STUDENT_STATUS,
  STUDENT_GENDER,
  TEACHER_STATUS,
  ACADEMIC_YEAR_STATUS,
  CLASS_STATUS,
  SECTION_STATUS,
  ENROLLMENT_STATUS,
  LEAD_STATUS,
  ATTENDANCE_STATUS,
  FEE_STATUS,
  PAYMENT_METHOD,
};
